services:
  altwiki:
    build: .
    image: altwiki:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://192.168.50.28:3001'
      APP_SECRET: '5c33c625b8fb1f298670856dad5d435088902222d30ef6197ee0f0ead8e1b877'
      DATABASE_URL: 'postgresql://docmost:atpass@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
      MAIL_DRIVER: 'smtp'
      MAIL_FROM_ADDRESS: 'khanalnitij20@gmail.com'
      MAIL_FROM_NAME: 'AltWiki'
      SMTP_HOST: 'smtp.gmail.com'
      SMTP_PORT: '587'
      SMTP_USERNAME: 'khanalnitij20@gmail.com'
      SMTP_PASSWORD: 'txipbuwdtzzuwrqo'
    ports:
      - "3001:3000"
    restart: unless-stopped
    volumes:
      - altwiki:/app/data/storage

  db:
    image: postgres:16-alpine
    # ports removed - only docmost container needs access
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: atpass
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  altwiki:
  db_data:
  redis_data:
